include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors : true
    library_private_types_in_public_api: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore